name: fluster_redd
description: A geospatial point clustering library for Dart to help provide spacing between markers in mapping solutions.
version: 1.2.0
homepage: https://github.com/eldobal/fluster-redd

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  mockito: ^5.0.2
  test: ^1.6.0
