name: fluster_redd
description: Solucion de clustes de marcadores Google Maps en Flutter para Redd SYSTEMS
version: 1.2.1
homepage: https://github.com/eldobal/fluster-redd

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  pedantic: ^1.7.0
  mockito: ^5.0.2
  test: ^1.6.0
